### ISSUE TITLE
The number of timestep do not exeeds 10 every time

### ISSUE THREAD

**Issue by DrDairiAek** [AcutronicRobotics/mara_examples#7]
Hi,
i'm using ROS2 MARA , all is ok no error, but when i run a simple code gg_random.py:
timesteps = 1024
    
    EPISODES = 100
    for e in range(EPISODES):
        state = env.reset()        
        for time in range(timesteps):
            #action = env.action_space.sample()            
            action = agent.act(env,state)            
            next_state, reward, done, _ = env.step(action)

The inner loop "for time in range(timesteps):" iteration is 10 every time i run it

**Comment by vmayoral** [comment]
Hi @kadirou31, thanks a lot for your interest and for trying things out with MARA. Unfortunately, Acutronic Robotics is not actively maintaining this anymore so I would kindly close your ticket and archive this repo.

Hope you find this material useful and all the best.
